from __future__ import annotations
from pathlib import Path


TOML_TEMPLATE = """\
# OpenNexus configuration — generated by `nexus init`
# Edit freely. Run `nexus init` again to regenerate.

[user]
name = {name!r}
timezone = {timezone!r}
role = {role!r}

[nexus]
data_dir = "~/.nexus"
notion_cache_dir = "~/.nexus/notion_cache"
timezone = {timezone!r}

[llm]
provider = {provider!r}
model = {model!r}
api_key = {api_key!r}
base_url = {base_url!r}
embed_model = {embed_model!r}
model_code = ""
model_reasoning = ""

[memory]
chroma_dir = "~/.nexus/chroma"
notion_collection = "notion_chunks"
conversation_collection = "conversation_history"
file_collection = "file_index"
top_k = 5
chunk_strategy = "heading"

[server]
host = "127.0.0.1"
port = 8000
frontend_dist = "./frontend/dist"
open_browser_on_start = true

[scheduler]
digest_cron = "0 8 * * *"
notion_sync_cron = "*/15 * * * *"
reindex_cron = "0 2 * * *"

[digest]
write_to_notion = {write_to_notion}
print_to_terminal = true

[connectors.weather]
latitude = {lat}
longitude = {lon}
location_name = {city!r}

[connectors.rss]
sources = [
  "https://hnrss.org/frontpage",
  "https://tldr.tech/api/rss/tech",
]

{connector_sections}
"""

CONNECTOR_SECTION = """\
[connectors.{name}]
enabled = {enabled}
"""

ALL_CONNECTORS = ["notion", "github", "gmail", "calendar", "classroom", "discord"]


def _detect_timezone() -> str:
    try:
        from tzlocal import get_localzone
        return str(get_localzone())
    except Exception:
        return "UTC"


def run_init(output_path: Path | None = None) -> None:
    import questionary
    from rich.console import Console
    from rich.panel import Panel

    console = Console()
    output_path = output_path or Path("nexus.toml")

    console.print(Panel(
        "[bold gold1]Welcome to OpenNexus[/bold gold1]\nLet's set up your personal intelligence layer.",
        border_style="dim"
    ))

    if output_path.exists():
        overwrite = questionary.confirm(f"{output_path} already exists. Overwrite?", default=False).ask()
        if not overwrite:
            console.print("[dim]Aborted.[/dim]")
            return

    name = questionary.text("Your name:", default="User").ask() or "User"
    detected_tz = _detect_timezone()
    timezone = questionary.text("Timezone:", default=detected_tz).ask() or detected_tz
    role = questionary.text("Your role (e.g. developer, student, researcher):", default="").ask() or ""

    provider = questionary.select(
        "LLM provider:",
        choices=[
            questionary.Choice("Ollama (local, free, private)", value="ollama"),
            questionary.Choice("OpenAI (API key required)", value="openai"),
            questionary.Choice("Anthropic (API key required)", value="anthropic"),
        ],
    ).ask()

    model_defaults = {
        "ollama": "llama3.2",
        "openai": "gpt-4o-mini",
        "anthropic": "claude-haiku-4-5-20251001",
    }
    embed_defaults = {
        "ollama": "nomic-embed-text",
        "openai": "text-embedding-3-small",
        "anthropic": "",
    }

    model = questionary.text("Model name:", default=model_defaults[provider]).ask() or model_defaults[provider]

    api_key = ""
    base_url = ""
    if provider == "ollama":
        base_url = questionary.text("Ollama base URL:", default="http://localhost:11434").ask() or "http://localhost:11434"
    else:
        api_key = questionary.password(f"{provider.capitalize()} API key:").ask() or ""

    embed_model = questionary.text(
        "Embedding model:",
        default=embed_defaults[provider],
    ).ask() or embed_defaults[provider]

    enabled_connectors = questionary.checkbox(
        "Which connectors to enable?",
        choices=ALL_CONNECTORS,
        default=["notion", "github"],
    ).ask() or []

    city = questionary.text("Your city (for weather):", default="Your City").ask() or "Your City"
    lat_str = questionary.text("Latitude (e.g. 13.7563):", default="0.0").ask() or "0.0"
    lon_str = questionary.text("Longitude (e.g. 100.5018):", default="0.0").ask() or "0.0"

    write_to_notion = "true" if "notion" in enabled_connectors else "false"

    connector_sections = "\n".join(
        CONNECTOR_SECTION.format(name=c, enabled="true" if c in enabled_connectors else "false")
        for c in ALL_CONNECTORS
    )

    content = TOML_TEMPLATE.format(
        name=name,
        timezone=timezone,
        role=role,
        provider=provider,
        model=model,
        api_key=api_key,
        base_url=base_url,
        embed_model=embed_model,
        write_to_notion=write_to_notion,
        lat=lat_str,
        lon=lon_str,
        city=city,
        connector_sections=connector_sections,
    )

    output_path.write_text(content, encoding="utf-8")
    console.print(f"\n[green]✓[/green] Config written to [bold]{output_path}[/bold]")

    if enabled_connectors:
        console.print("\n[dim]Next steps:[/dim]")
        for c in enabled_connectors:
            service = "google" if c in ("gmail", "calendar", "classroom") else c
            console.print(f"  nexus connect {service}")
    console.print("\nThen run: [bold]nexus serve[/bold]")
